import re

# English to Turkish Specification Mapping
SPEC_MAP = {
    "Network": "Şebeke",
    "Technology": "Teknoloji",
    "Launch": "Lansman",
    "Announced": "Duyurulma Tarihi",
    "Status": "Durum",
    "Body": "Gövde",
    "Dimensions": "Boyutlar",
    "Weight": "Ağırlık",
    "Build": "Gövde Malzemesi",
    "SIM": "SIM Kart",
    "Display": "Ekran",
    "Type": "Ekran Teknolojisi",
    "Size": "Ekran Boyutu",
    "Resolution": "Ekran Çözünürlüğü",
    "Protection": "Ekran Dayanıklılığı",
    "Platform": "İşletim Sistemi ve İşlemci",
    "OS": "İşletim Sistemi",
    "Chipset": "Yonga Seti",
    "CPU": "Ana İşlemci (CPU)",
    "GPU": "Grafik İşlemcisi (GPU)",
    "Memory": "Bellek ve Depolama",
    "Card slot": "Hafıza Kartı Desteği",
    "Internal": "Dahili Depolama",
    "Main Camera": "Arka Kamera",
    "Selfie camera": "Ön Kamera",
    "Sound": "Ses",
    "Loudspeaker": "Hoparlör",
    "3.5mm jack": "3.5mm Ses Çıkışı",
    "Comms": "Kablosuz Bağlantılar",
    "WLAN": "Wi-Fi",
    "Bluetooth": "Bluetooth",
    "Positioning": "Navigasyon",
    "NFC": "NFC",
    "Radio": "Radyo",
    "USB": "USB Bağlantısı",
    "Features": "Özellikler",
    "Sensors": "Sensörler",
    "Battery": "Batarya",
    "Charging": "Şarj",
    "Misc": "Diğer",
    "Colors": "Renk Seçenekleri",
    "Price": "Fiyat",
    "Models": "Modeller",
    "SAR": "SAR Değeri",
    "SAR EU": "SAR Değeri (AB)",
    "Video": "Video Kayıt",
    "Single": "Tek Kamera",
    "Dual": "Çift Kamera",
    "Triple": "Üçlü Kamera",
    "Quad": "Dörtlü Kamera",
    "RAM": "Bellek (RAM)",
    "storage_gb": "Dahili Depolama (GB)",
    "ram_gb": "Bellek (RAM) (GB)",
    "battery_mah": "Batarya Kapasitesi (mAh)",
    "screen_size_inch": "Ekran Boyutu (İnç)"
}

VALUE_TRANSLATIONS = {
    "Glass front": "Cam ön yüzey",
    "Glass back": "Cam arka yüzey",
    "Plastic back": "Plastik arka yüzey",
    "Plastic frame": "Plastik çerçeve",
    "Aluminum frame": "Alüminyum çerçeve",
    "Stainless steel frame": "Paslanmaz çelik çerçeve",
    "Titanium frame": "Titanyum çerçeve",
    "Eco leather back": "Suni deri arka yüzey",
    "aluminum back": "Alüminyum arka yüzey",
    "Water resistant": "Suya Dayanıklılık",
    "Dust resistant": "Toza Dayanıklılık",
    "IP68 dust/water resistant": "IP68 Suya ve Toza Dayanıklılık",
    "Scratch-resistant glass": "Çizilmeye Dirençli Cam",
    "oleophobic coating": "Parmak İzi Tutmaz Kaplama",
    "refresh rate": "yenileme hızı",
    "peak brightness": "maksimum parlaklık",
    "resolution": "çözünürlük",
    "aspect ratio": "ekran oranı",
    "protection": "koruma",
    "pixels": "piksel",
    "density": "piksel yoğunluğu",
    "screen-to-body ratio": "ekran gövde oranı",
    "Triple": "Üçlü",
    "Quad": "Dörtlü",
    "Dual": "Çift",
    "Single": "Tek",
    "Wide": "Geniş Açı",
    "Ultrawide": "Ekstra Geniş Açı",
    "Telephoto": "Telefoto",
    "Macro": "Makro",
    "Depth": "Derinlik Algısı",
    "Aperture": "Diyafram Açıklığı",
    "Focal length": "Odak Uzaklığı",
    "Optical Image Stabilization": "Optik Görüntü Sabitleyici (OIS)",
    "PDAF": "Faz Algılamalı Otomatik Odaklama",
    "dual-led flash": "Çift LED Flaş",
    "panorama": "Panoramik",
    "core": "çekirdek",
    "performance cores": "performans çekirdeği",
    "efficiency cores": "verimlilik çekirdeği",
    "upgradable to": "yükseltilebilir",
    "Fingerprint": "Parmak İzi Okuyucu",
    "Accelerometer": "İvmeölçer",
    "Gyro": "Jiroskop",
    "Proximity": "Yakınlık Sensörü",
    "Compass": "Pusula",
    "Barometer": "Barometre",
    "Light sensor": "Işık Sensörü",
    "Heart rate": "Nabız Ölçer",
    "Fast charging": "Hızlı Şarj",
    "Wireless charging": "Kablosuz Şarj",
    "Available": "Mevcut",
    "Coming soon": "Yakında",
    "Announced": "Duyurulma",
    "Released": "Satışa Çıktı",
    "cellular model only": "sadece hücresel model",
    "No": "Yok",
    "Yes": "Var",
    "About": "Yaklaşık",
    "inches": "İnç",
    "Black": "Siyah",
    "White": "Beyaz",
    "Blue": "Mavi",
    "Red": "Kırmızı",
    "Green": "Yeşil",
    "Yellow": "Sarı",
    "Purple": "Mor",
    "Pink": "Pembe",
    "Silver": "Gümüş",
    "Gold": "Altın",
    "Gray": "Gri",
    "Grey": "Gri",
    "Orange": "Turuncu",
    "Brown": "Kahverengi",
    "Space Gray": "Uzay Grisi",
    "Space Grey": "Uzay Grisi",
    "Space Black": "Uzay Siyahı",
    "Midnight": "Gece Yarısı",
    "Starlight": "Yıldız Işığı",
    "Graphite": "Grafit",
    "Sierra Blue": "Sierra Mavisi",
    "Pacific Blue": "Pasifik Mavisi",
    "Deep Purple": "Derin Mor",
    "Natural Titanium": "Doğal Titanyum",
    "Blue Titanium": "Mavi Titanyum",
    "White Titanium": "Beyaz Titanyum",
    "Black Titanium": "Siyah Titanyum",
    "Rose Gold": "Roze Altın",
    "Matte Black": "Mat Siyah",
    "Jet Black": "Simsiyah",
    "Phantom Black": "Fantom Siyahı",
    "Phantom Silver": "Fantom Gümüşü",
    "Cloud Blue": "Bulut Mavisi",
    "Cloud Pink": "Bulut Pembesi",
    "Prism White": "Prizma Beyazı",
    "Prism Black": "Prizma Siyahı",
    "Cosmic Gray": "Kozmik Gri",
    "Cosmic Black": "Kozmik Siyah",
    "Aura Glow": "Aura Işıltısı",
    "Aura Blue": "Aura Mavisi",
    "Aura Black": "Aura Siyahı",
    "Aura White": "Aura Beyazı",
    "Class": "Sınıf",
    "drops without defects": "hatasız düşme"
}

def map_specs_to_turkish(specs):
    if not isinstance(specs, dict):
        return specs
        
    mapped = {}
    for key, value in specs.items():
        turkish_key = SPEC_MAP.get(key, key)
        
        if isinstance(value, str):
            translated_value = value
            for eng, tr in VALUE_TRANSLATIONS.items():
                # Use regex for whole word and case-insensitive matching
                pattern = r'\b' + re.escape(eng) + r'\b'
                translated_value = re.sub(pattern, tr, translated_value, flags=re.IGNORECASE)
            mapped[turkish_key] = translated_value.strip()
        elif isinstance(value, dict):
            mapped[turkish_key] = map_specs_to_turkish(value)
        else:
            mapped[turkish_key] = value
            
    return mapped
